Hw7
iionov-hub/geekshop pull request #7
Opened 2021-03-15 14:31 UTC by iionov-hub

2021-03-15 15:42 UTC, Vokler requested changes

2021-03-15 15:42 UTC, Vokler commented on adminapp/forms.py
> +        def __init__(self, *args, **kwargs):
У вас функция `__init__()` идет для класса `Meta`, а должна быть для `ProductAdminRegistrationForm`

2021-03-15 16:03 UTC, iionov-hub commented on adminapp/forms.py
> +        def __init__(self, *args, **kwargs):
Точно, спасибо большое, исправил

2021-03-16 10:43 UTC, Vokler approved these changes

2021-03-16 10:43 UTC, merged